server:
  port: ${peer1.server.port}

spring:
  zipkin:
    base-url: ${spring.zipkin.base-url}
  profiles: peer1
  datasource:
    url: "jdbc:mysql://${spring.mysql.host}:${spring.mysql.port}/${spring.mysql.database}?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8"
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

eureka:
  client:
    service-url:
      defaultZone: ${peer1.eureka.client.serviceUrl.defaultZone}

#TC配置信息
tx-lcn:
  client:
    manager-address: ${peer1.tx-lcn.client.manager-address}
